### ISSUE TITLE
[SUGGESTION] Add text on BCC

### ISSUE THREAD

**Issue by koppor** [email-charter/email-charter.github.io#3]
Proposal for a text:

---

### 11. Move Persons from CC to BCC

Continuing the conversation with a smaller group but still want to keep others in the loop? Move them to BCC. By doing this, you prevent them from receiving unnecessary follow-ups, while still keeping them informed of the initial communication. It's an efficient way to reduce email clutter. When using BCC, it's courteous to mention it in the body of the email. Start with "BCC: [names]" as the first line to ensure transparency.

---

Maybe, there should be a link at the mail to this page giving more background, is that usage of BCC is not often used yet. Maybe we add ``You can include a link to the rules afterwards: ` - reducing emails by following the [Email Charter](https://email-charter.github.io/)` ``?

More background: https://www.theatlantic.com/entertainment/archive/2017/04/im-moving-you-to-bcc/522885/

**Comment by b-kennedy0** [comment]
Webpage updated https://email-charter.github.io/#11-move-people-from-cc-to-bcc - Thanks @koppor
