### ISSUE TITLE
Alt-text instruction in charter item #3

### ISSUE THREAD

**Issue by kfergy** [email-charter/email-charter.github.io#7]
*Title:*  
Add instructions to add alt-text/image description to embedded/inline images (item #3)

*Description:*  
In item #3 of the charter, **3. Attack Attachments**, embedding images would benefit from an additional step of adding alt-text/descriptive text to the images used.

Here are [instructions according to Microsoft for Outlook](https://support.microsoft.com/en-gb/office/video-improve-image-accessibility-in-email-e93969e3-21c1-47ad-a4c5-0e5fb868a7f8), and [general instructions irrespective of email provider](https://www.audioeye.com/post/the-surprising-gap-in-email-accessibility/) (though with an example for Gmail). 

I understand that the reasoning of the Charter is to streamline emails; I bring this up so that this streamlining is not unintentionally excluding users/recipients and adheres to emerging accessibility guidelines for (corporate) communication. The absence of incorporating accessibility into the Charter would likely weaken it's uptake.

**Comment by b-kennedy0** [comment]
@kfergy Thanks for the suggestion - the page has been updated
